# Generated by Django 5.0.6 on 2024-06-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(blank=True, null=True, to='books.author')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.edition')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.genre')),
            ],
            options={
                'unique_together': {('title', 'edition')},
            },
        ),
    ]
